name: Build Gn

on:
  schedule:
    - cron: '* * 1 * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
  release:
    types: [published]

jobs:
  build:
    name: Build Gn
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Check Dir
        run: ls -la

      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build Gn
        id: build
        with:
          arch: aarch64
          distro: ubuntu18.04

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # The shell to run commands with in the container
          shell: /bin/bash

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            apt-get update -y
            apt-get install git python ninja-build build-essential clang llvm -y

          # Produce a binary artifact and place it in the mounted volume
          run: |
            git clone https://gn.googlesource.com/gn
            cd gn
            python build/gen.py
            ninja -C out
            cp out/gn /artifacts/gn
            echo "Produced Gn at $(ls /artifacts)"

      - name: Prepare Binary
        run: |
          ls artifacts
          zip -r artifacts/gn.zip artifacts/gn
          ls -l artifacts/gn.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Gn Build"
          files: |
            gn.zip
          draft: true
