name: Build Gn

on: workflow_dispatch

jobs:
  build:
    name: Build Gn
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
